"""Add order to SongsQueue

Revision ID: 2a21e78eecb5
Revises: a1f155c4d7a0
Create Date: 2024-02-27 17:32:57.690853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a21e78eecb5'
down_revision = 'a1f155c4d7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_queue', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
