"""Add played field to songsQueue

Revision ID: 3fce8045220a
Revises: 164e67756d0a
Create Date: 2024-02-29 16:55:28.072030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fce8045220a'
down_revision = '164e67756d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('played', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_queue', schema=None) as batch_op:
        batch_op.drop_column('played')

    # ### end Alembic commands ###
