"""Add is_embeddable to SongsQueue

Revision ID: a1f155c4d7a0
Revises: 4fe6ff61f3f2
Create Date: 2024-02-26 19:09:43.234365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1f155c4d7a0'
down_revision = '4fe6ff61f3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_embeddable', sa.Boolean(), nullable=True))
        batch_op.alter_column('added_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_queue', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('is_embeddable')

    # ### end Alembic commands ###
